### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by goxberry** [LLNL/libROM#1]
Add hooks for continuous integration testing of libROM.

**Comment by rw-anderson** [comment]
Giving permissions to Travis CI requires being an admin "on the account that owns the repository".  Apparently I am not.  Are you @goxberry ?

**Comment by samyakdarshan** [comment]
Can we use Jenkins pipeline instead of travis CI?

**Comment by chldkdtn** [comment]
CI has been added by @kevinhkhuynh in the past.
