### ISSUE TITLE
Building MFEM dependency frozen due to Cmake consuming too much RAM

### ISSUE THREAD

**Issue by axla-io** [LLNL/libROM#127]
## Issue
Cmake creates too many parallel processes when installing `MFEM`. They consume all available RAM and causes the program to freeze.

## Affected
I encountered this problem when installing libROM with `MFEM` dependency on two different laptops with 8Gb RAM.

## Fix
Change the `-j` flag to `-j8`, or some other resonable finite number, in the cmake compilation of `MFEM` in /[scripts/setup.sh](https://github.com/LLNL/libROM/tree/master/scripts/setup.sh)

**Comment by chldkdtn** [comment]
Thank you, @axla-io !
