### ISSUE TITLE
missing mesh in non-linear elasticity prom

### ISSUE THREAD

**Issue by gokhalen** [LLNL/libROM#184]
I'm trying to run the non-linear elasticity prom

https://www.librom.net/examples.html

using @dreamer2368 's Docker container.

The command is 

```
./nonlinear_elasticity_global_rom --mesh "../../../dependencies/mfem/data/beam-hex-nurbs.mesh" --offline -dt 0.01 -tf 5.0 -s 14 -vs 10 -sc 3.9 -id 0
```

I'm not able to find the mesh 'beam-hex-nurbs.mesh' in the Docker container.  

In examples/data I see

./examples/data/periodic-hexagon.mesh
./examples/data/star.mesh
./examples/data/inline-quad.mesh
./examples/data/periodic-square.mesh
./examples/data/beam-quad.mesh
./examples/data/beam-tri.mesh
./build/examples/data/periodic-hexagon.mesh
./build/examples/data/star.mesh
./build/examples/data/inline-quad.mesh
./build/examples/data/periodic-square.mesh
./build/examples/data/beam-quad.mesh
./build/examples/data/beam-tri.mesh

But not the mesh beam-hex-nurbs.mesh that I require.

Any help is much appreciated.

Nachiket

**Comment by dreamer2368** [comment]
Can you provide how you `cmake`? They should be copied from the source directory.

In the [librom_env](https://hub.docker.com/repository/docker/dreamer2368/librom_env/general) container with a source directory `$SRCDIR`, you can cmake as below:
```
cmake $SRCDIR -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_MFEM=${USE_MFEM} -DMFEM_USE_GSLIB=${MFEM_USE_GSLIB}
```

This is also in the [instruction](https://hub.docker.com/repository/docker/dreamer2368/librom_env/general) in the container.

**Comment by gokhalen** [comment]
I think I understand now. I have to get the file I was looking for from mfem.

**Comment by dreamer2368** [comment]
@gokhalen , I'm closing this issue unless you have any further problem.
