### ISSUE TITLE
SPACK build failing

### ISSUE THREAD

**Issue by ajkmr-data** [LLNL/libROM#90]
Hello.
Build fails on ubuntu20.04 after installing a bunch of libraries. Installation machine description:

linux-ubuntu20.04-skylake_avx512/gcc-9.3.0

Error message:
***********
==> Warning: Missing a source id for librom@develop
==> Error: RuntimeError: Cannot generate configure: missing dependencies: autoconf, automake, libtool.

Please add the following lines to the package:

    depends_on('autoconf', type='build', when='@develop')
    depends_on('automake', type='build', when='@develop')
    depends_on('libtool', type='build', when='@develop')

Update the version (when='@develop') as needed.

/home/user/git/spack/lib/spack/spack/build_systems/autotools.py:324, in _require_build_deps:
        321            msg += ("    depends_on('{0}', type='build', when='@{1}')\n"
        322                    .format(dep, spec.version))
        323
  >>    324        msg += "\nUpdate the version (when='@@{0}') as needed.".format(spec.version)
        325        raise RuntimeError(msg)
********************************

**Comment by lujiabo98** [comment]
@ajikmr Hello. I met the same problem with you. Would you please tell me how to solve the problem? Thanks a lot!
